server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: scraping_db
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

driver:
  path: /home/alex/work/settings/chromedriver